### ISSUE TITLE
RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by fakerybakery** [lucidrains/self-rewarding-lm-pytorch#15]
Thanks for implementing this!
I'm using MPS and getting the error `RuntimeError: Placeholder storage has not been allocated on MPS device!`.
Is there any way to fix this?
Thanks!

**Comment by lucidrains** [comment]
@fakerybakery hey yup, i put in a fix

**Comment by fakerybakery** [comment]
Thx!
